### ISSUE TITLE
[FEAT] Add timer "seconds lapsed" 

### ISSUE THREAD

**Issue by BilelJegham** [GeoGuess/Geoguess#154]
**Is your feature request related to a problem? Please describe.**
Add timer "seconds lapsed" per round and sum per game

**Describe the solution you'd like**
 1. Add in-game interface
 2. Add in history game detail

Link to #152

**Comment by BilelJegham** [comment]
Step2: 
 Include "total seconds lapsed" in New score mode

**Comment by BilelJegham** [comment]
Hi @tululum 
Step 1 and step 2 ready in #156 

Can you give me feedback ?
https://deploy-preview-156--geoguess2.netlify.app/

You can select score mode "Time" .
![image](https://user-images.githubusercontent.com/20130405/114754447-e20b3400-9d58-11eb-89cf-abbe3eb8e3a2.png)

**Comment by tululum** [comment]
Wow, that was fast. :O But no timer shows up for me at all. :/
https://youtu.be/QLJZVnh5xGA

**Comment by BilelJegham** [comment]
I only add it at the end of the game in History Page.
![image](https://user-images.githubusercontent.com/20130405/114780156-4e952b80-9d77-11eb-8779-a4d7dc692ed9.png)

Add it in the Header can be great 👍

**Comment by tululum** [comment]
Ohh, ok :) Yeah, adding it to the header and possibly even to the round results would be super cool :) :

![image](https://user-images.githubusercontent.com/67554090/114821025-3a295100-9dc0-11eb-9192-abf180194355.png)


Also a small bug: after a 2-player game, the time for every round is shown as Not a Number:
![image](https://user-images.githubusercontent.com/67554090/114820509-62648000-9dbf-11eb-91eb-7d87a446c41d.png)

Otherwise looks good :)

If I may propose, it would be super awesome to make this cooperative mode now before doing the group versus play (step 3). For cooperative play all players would spawn and move as normal, but only one single guess could be made for the whole group (once anyone makes a guess, the round ends for everyone). Also, the score would be a single score shared with all players in the game. So when playing with friends you can move around independently, but all guessing and scoring is shared with all players - so basically they play as a group, together, talking about where they think they are, what they see, discussing options and then making a one single best guess they all agree to, receive score together (since everyone collaborated on the guess) and move to the next round.

I think this cooperative play (well, basically group scoring) shouldn't hopefully be as difficult to do as 3vs3 for example, because it only consists of two (seemingly small) changes:
1. A one single guess is made for the whole group - when the guess is made by any player, the round ends for everyone (this functionality is already implemented in Pick a country TimeAttack mode, so hopefully can be reused with only minor changes)
2. All players share a common score.

Let me know what you think ;) Anyway, thanks, its looking good :)
